### ISSUE TITLE
Suggestion to Cite Apollo: First to Apply Proxy Tuning to Multilingual Settings

### ISSUE THREAD

**Issue by NuoJohnChen** [davidanugraha/proxylm#1]
Hi, davidanugraha. Thank you for your great contribution with this impressive work! 
We would like to kindly draw your attention to our work, Apollo, which is the first to apply proxy tuning to multilingual settings, achieving state-of-the-art results for multilingual medical LLMs up to 70B.  We believe referencing our work could enhance the context of your related work. You can find our work here: [Github](https://github.com/FreedomIntelligence/Apollo), [ArXiv](https://arxiv.org/pdf/2403.03640)
Thank you for your consideration!

**Comment by davidanugraha** [comment]
Hi NuoJohnChen. Thank you for the feedback! We will reference your work for our related work in our future revision.

[Update March 2025] We have referenced your work for our related work in our newest revision!
